name: Auto Pull Request

on:
  push:
    branches-ignore:
      - deploy   # toutes les branches sauf deploy

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "PR automatique - ${{ github.ref_name }}"
          body: "PR créée automatiquement depuis la branche ${{ github.ref_name }}"
          base: main        # branche cible
          draft: false
